# Generated by Django 4.2.5 on 2023-09-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
