# Generated by Django 4.2.5 on 2023-09-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.course', verbose_name='курс'),
        ),
    ]
