# Generated by Django 4.2.5 on 2023-09-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_pay_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': 'Птатеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='data',
            new_name='date',
        ),
    ]
